version: '3.8'

services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      # 一覧は以下で確認可能
      # http://localhost:4566/_localstack/health
      - SERVICES=apigateway,dynamodb,lambda,logs,s3
      - DEBUG=1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
